# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_of_allocation',
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='Daily', max_length=7),
            preserve_default=False,
        ),
    ]
