# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0002_auto_20190710_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeepingManagement.Task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeepingManagement.Worker')),
            ],
        ),
    ]
