# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0003_adminmanager_workerskillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_allocation', models.DateTimeField()),
                ('task_to_be_performed_by', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeepingManagement.Asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeepingManagement.Task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housekeepingManagement.Worker')),
            ],
        ),
        migrations.RenameField(
            model_name='workerskillset',
            old_name='tasks',
            new_name='task',
        ),
    ]
