# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0004_auto_20190710_2345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerskillset',
            unique_together=set([('worker', 'task')]),
        ),
    ]
