# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0005_auto_20190710_2351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocatedtasks',
            unique_together=set([('asset', 'task', 'worker')]),
        ),
    ]
