# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeepingManagement', '0006_auto_20190711_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedtasks',
            name='time_of_allocation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
